import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1782159822766 implements MigrationInterface {
    name = 'InitialSchema1782159822766'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`yjs_documents\` (\`name\` varchar(255) NOT NULL, \`state\` longblob NOT NULL, \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`name\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_permissions\` (\`id\` varchar(36) NOT NULL, \`document_id\` int NOT NULL, \`user_id\` int NOT NULL, \`role\` enum ('owner', 'editor', 'viewer') NOT NULL DEFAULT 'viewer', \`can_read\` tinyint NOT NULL DEFAULT 1, \`can_write\` tinyint NOT NULL DEFAULT 0, \`can_delete\` tinyint NOT NULL DEFAULT 0, \`can_share\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_7313984ff65bd406b5ef0ab740\` (\`document_id\`, \`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`file_system_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`description\` varchar(500) NULL, \`itemType\` enum ('folder', 'document') NOT NULL, \`author\` varchar(20) NULL, \`content\` text NULL, \`thumb_url\` varchar(255) NULL DEFAULT '', \`documentType\` enum ('text', 'image', 'word', 'excel', 'other') NULL, \`parentId\` int NULL, \`sortOrder\` int NOT NULL DEFAULT '0', \`creator_id\` int NOT NULL, \`visibility\` enum ('private', 'public', 'shared') NOT NULL DEFAULT 'private', \`isDeleted\` tinyint NOT NULL DEFAULT 0, \`is_collaboration_enabled\` tinyint NOT NULL DEFAULT 0, \`created_time\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_time\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_c68be06ea43873457839846478\` (\`parentId\`), INDEX \`IDX_920d8d3c8f96f3f586e1860690\` (\`creator_id\`, \`isDeleted\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`username\` varchar(50) NOT NULL, \`email\` varchar(100) NOT NULL, \`password\` varchar(255) NOT NULL, \`avatar\` varchar(500) NULL COMMENT '用户头像URL', \`displayName\` varchar(100) NULL COMMENT '昵称/显示名称', \`phone\` varchar(20) NULL COMMENT '手机号', \`bio\` text NULL COMMENT '个人简介', \`location\` varchar(100) NULL COMMENT '所在地', \`website\` varchar(200) NULL COMMENT '个人网站', \`organization\` varchar(100) NULL COMMENT '公司/组织', \`position\` varchar(100) NULL COMMENT '职位', \`statusColor\` varchar(10) NULL COMMENT '用户状态颜色(协作时显示)', \`onlineStatus\` enum ('online', 'offline', 'away', 'busy') NOT NULL COMMENT '在线状态' DEFAULT 'offline', \`lastActiveAt\` timestamp NULL COMMENT '最后活跃时间', \`allowCollaboration\` tinyint NOT NULL COMMENT '是否接受协作邀请' DEFAULT 1, \`showOnlineStatus\` tinyint NOT NULL COMMENT '是否显示在线状态' DEFAULT 1, \`refreshToken\` varchar(500) NULL, \`tokenVersion\` int NOT NULL COMMENT 'Token版本号,用于单点登录强制失效旧token' DEFAULT '0', \`isActive\` tinyint NOT NULL COMMENT '账号是否激活' DEFAULT 1, \`lastLoginAt\` timestamp NULL COMMENT '最后登录时间', \`lastEmailChangedAt\` timestamp NULL COMMENT '上次邮箱修改时间（用于冷却期检查）', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_versions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`document_id\` int NOT NULL, \`version_number\` int NOT NULL, \`compressed_content\` longblob NOT NULL, \`content_size\` int NOT NULL, \`content_hash\` varchar(64) NOT NULL, \`author_id\` int NOT NULL, \`change_description\` varchar(500) NULL, \`is_auto_save\` tinyint NOT NULL DEFAULT 1, \`is_restore\` tinyint NOT NULL DEFAULT 0, \`is_delta\` tinyint NOT NULL DEFAULT 0, \`base_version_id\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_c03a7c4a6e9f426f8be7575e24\` (\`created_at\`), INDEX \`IDX_09d162421c69e006f9416201d1\` (\`content_hash\`), INDEX \`IDX_a32135a8060e5e85038af17bd5\` (\`document_id\`, \`version_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`document_comments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`document_id\` int NOT NULL, \`user_id\` int NOT NULL, \`content\` text NOT NULL COMMENT '评论内容', \`quoted_text\` text NULL COMMENT '引用的原文', \`start_pos\` int NOT NULL COMMENT '起始位置（字符偏移）', \`end_pos\` int NOT NULL COMMENT '结束位置', \`resolved\` tinyint NOT NULL COMMENT '是否已解决' DEFAULT 0, \`resolved_by\` int NULL COMMENT '解决者ID', \`resolved_at\` timestamp NULL COMMENT '解决时间', \`parent_id\` int NULL COMMENT '父评论ID(用于回复)', \`reply_count\` int NOT NULL COMMENT '回复数量' DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp NULL COMMENT '软删除时间', INDEX \`IDX_33532225bce025fa2b2b93ad06\` (\`parent_id\`), INDEX \`IDX_9393ef33ff8817c0930a2dc17e\` (\`document_id\`, \`deleted_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`email_verification_codes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NOT NULL, \`code\` varchar(6) NOT NULL, \`type\` enum ('register', 'reset_password', 'change_email') NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`expires_at\` timestamp NOT NULL, \`is_used\` tinyint NOT NULL DEFAULT 0, \`used_at\` timestamp NULL, \`verify_attempts\` int NOT NULL COMMENT '验证尝试次数' DEFAULT '0', INDEX \`IDX_581ce944ea5ab6f4efd9fa64cc\` (\`expires_at\`), INDEX \`IDX_7abea591a9e28c381e941e6f78\` (\`email\`, \`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mail_quota_stats\` (\`id\` int NOT NULL AUTO_INCREMENT, \`provider\` enum ('qq', '163', 'total') NOT NULL COMMENT '邮件服务提供商', \`stat_date\` date NOT NULL COMMENT '统计日期', \`sent_count\` int NOT NULL COMMENT '已发送数量' DEFAULT '0', \`failed_count\` int NOT NULL COMMENT '失败数量' DEFAULT '0', \`quota_limit\` int NOT NULL COMMENT '配额限制', \`last_updated\` datetime(6) NOT NULL COMMENT '最后更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_ad60fe2ac9b2b98be6a5666481\` (\`provider\`, \`stat_date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mail_send_logs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`provider\` enum ('qq', '163') NOT NULL COMMENT '邮件服务提供商', \`recipient_email\` varchar(100) NOT NULL COMMENT '收件人邮箱', \`mail_type\` enum ('verification', 'reset_password', 'notification') NOT NULL COMMENT '邮件类型', \`subject\` varchar(200) NULL COMMENT '邮件主题', \`status\` enum ('success', 'failed', 'retry') NOT NULL COMMENT '发送状态', \`error_message\` text NULL COMMENT '错误信息', \`retry_count\` int NOT NULL COMMENT '重试次数' DEFAULT '0', \`ip_address\` varchar(45) NULL COMMENT '请求IP地址', \`response_time\` int NULL COMMENT '响应时间（毫秒）', \`created_at\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_d37bcb7f89f0bed89ce045def4\` (\`recipient_email\`), INDEX \`IDX_31d3807af9b31f2d18fe9cacf9\` (\`provider\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`mail_rate_limits\` (\`id\` int NOT NULL AUTO_INCREMENT, \`identifier\` varchar(100) NOT NULL COMMENT '标识符（IP或邮箱）', \`limit_type\` enum ('ip_daily', 'email_hourly', 'same_operation') NOT NULL COMMENT '限流类型', \`count\` int NOT NULL COMMENT '计数' DEFAULT '1', \`operation_type\` varchar(50) NULL COMMENT '操作类型', \`window_start\` datetime NOT NULL COMMENT '时间窗口开始', \`expires_at\` datetime NOT NULL COMMENT '过期时间', \`created_at\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_1bed750e4cba756713d98e8a46\` (\`expires_at\`), UNIQUE INDEX \`IDX_99bba8d4a120765daf11e2dbbc\` (\`identifier\`, \`limit_type\`, \`window_start\`, \`operation_type\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`document_permissions\` ADD CONSTRAINT \`FK_2f7f2d4832f753802b0ff3a0a48\` FOREIGN KEY (\`document_id\`) REFERENCES \`file_system_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_permissions\` ADD CONSTRAINT \`FK_a5d8c33068e9946e29d56e08773\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`file_system_items\` ADD CONSTRAINT \`FK_cefcb1922ce99da318dbf63c12d\` FOREIGN KEY (\`creator_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`file_system_items\` ADD CONSTRAINT \`FK_c68be06ea438734578398464781\` FOREIGN KEY (\`parentId\`) REFERENCES \`file_system_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_versions\` ADD CONSTRAINT \`FK_ac75577bca976d6d581b0f459b6\` FOREIGN KEY (\`document_id\`) REFERENCES \`file_system_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_versions\` ADD CONSTRAINT \`FK_af1f7dbb40de6a99ec5783f7b2f\` FOREIGN KEY (\`author_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_comments\` ADD CONSTRAINT \`FK_cc25441dacae9903dfb4bd9d15c\` FOREIGN KEY (\`document_id\`) REFERENCES \`file_system_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_comments\` ADD CONSTRAINT \`FK_d70fdf9bf6c395f48eecb690083\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_comments\` ADD CONSTRAINT \`FK_812495933c815938e15fdaef518\` FOREIGN KEY (\`resolved_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`document_comments\` ADD CONSTRAINT \`FK_33532225bce025fa2b2b93ad068\` FOREIGN KEY (\`parent_id\`) REFERENCES \`document_comments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`document_comments\` DROP FOREIGN KEY \`FK_33532225bce025fa2b2b93ad068\``);
        await queryRunner.query(`ALTER TABLE \`document_comments\` DROP FOREIGN KEY \`FK_812495933c815938e15fdaef518\``);
        await queryRunner.query(`ALTER TABLE \`document_comments\` DROP FOREIGN KEY \`FK_d70fdf9bf6c395f48eecb690083\``);
        await queryRunner.query(`ALTER TABLE \`document_comments\` DROP FOREIGN KEY \`FK_cc25441dacae9903dfb4bd9d15c\``);
        await queryRunner.query(`ALTER TABLE \`document_versions\` DROP FOREIGN KEY \`FK_af1f7dbb40de6a99ec5783f7b2f\``);
        await queryRunner.query(`ALTER TABLE \`document_versions\` DROP FOREIGN KEY \`FK_ac75577bca976d6d581b0f459b6\``);
        await queryRunner.query(`ALTER TABLE \`file_system_items\` DROP FOREIGN KEY \`FK_c68be06ea438734578398464781\``);
        await queryRunner.query(`ALTER TABLE \`file_system_items\` DROP FOREIGN KEY \`FK_cefcb1922ce99da318dbf63c12d\``);
        await queryRunner.query(`ALTER TABLE \`document_permissions\` DROP FOREIGN KEY \`FK_a5d8c33068e9946e29d56e08773\``);
        await queryRunner.query(`ALTER TABLE \`document_permissions\` DROP FOREIGN KEY \`FK_2f7f2d4832f753802b0ff3a0a48\``);
        await queryRunner.query(`DROP INDEX \`IDX_99bba8d4a120765daf11e2dbbc\` ON \`mail_rate_limits\``);
        await queryRunner.query(`DROP INDEX \`IDX_1bed750e4cba756713d98e8a46\` ON \`mail_rate_limits\``);
        await queryRunner.query(`DROP TABLE \`mail_rate_limits\``);
        await queryRunner.query(`DROP INDEX \`IDX_31d3807af9b31f2d18fe9cacf9\` ON \`mail_send_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_d37bcb7f89f0bed89ce045def4\` ON \`mail_send_logs\``);
        await queryRunner.query(`DROP TABLE \`mail_send_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_ad60fe2ac9b2b98be6a5666481\` ON \`mail_quota_stats\``);
        await queryRunner.query(`DROP TABLE \`mail_quota_stats\``);
        await queryRunner.query(`DROP INDEX \`IDX_7abea591a9e28c381e941e6f78\` ON \`email_verification_codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_581ce944ea5ab6f4efd9fa64cc\` ON \`email_verification_codes\``);
        await queryRunner.query(`DROP TABLE \`email_verification_codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_9393ef33ff8817c0930a2dc17e\` ON \`document_comments\``);
        await queryRunner.query(`DROP INDEX \`IDX_33532225bce025fa2b2b93ad06\` ON \`document_comments\``);
        await queryRunner.query(`DROP TABLE \`document_comments\``);
        await queryRunner.query(`DROP INDEX \`IDX_a32135a8060e5e85038af17bd5\` ON \`document_versions\``);
        await queryRunner.query(`DROP INDEX \`IDX_09d162421c69e006f9416201d1\` ON \`document_versions\``);
        await queryRunner.query(`DROP INDEX \`IDX_c03a7c4a6e9f426f8be7575e24\` ON \`document_versions\``);
        await queryRunner.query(`DROP TABLE \`document_versions\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_920d8d3c8f96f3f586e1860690\` ON \`file_system_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_c68be06ea43873457839846478\` ON \`file_system_items\``);
        await queryRunner.query(`DROP TABLE \`file_system_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_7313984ff65bd406b5ef0ab740\` ON \`document_permissions\``);
        await queryRunner.query(`DROP TABLE \`document_permissions\``);
        await queryRunner.query(`DROP TABLE \`yjs_documents\``);
    }

}
