name: 自动部署到云服务器

on:
  push:
    branches: [ main, master, dev-pzj ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 安装依赖
      run: |
        npm install -g pnpm
        pnpm install --frozen-lockfile
        
    - name: 构建项目
      run: pnpm run build
      
    - name: 运行测试
      run: pnpm run test
      
    - name: 部署到服务器
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev-pzj'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/deploy/docs-manage
          git pull origin ${{ github.ref_name }}
          docker-compose down
          docker-compose up --build -d
          docker system prune -f